name: sport
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  rxdart: ^0.27.2
  bot_toast: ^4.1.3
  supabase_flutter: ^2.5.8
  shared_preferences: ^2.2.2
  freezed:
  freezed_annotation:
  json_serializable:
  get_it:
  lottie:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner:
  freezed:

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
